name: Release
on:
  push:
    branches:
      - main
      - develop
jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
